#!/bin/sh
export PYTHONPATH=/home/marcelo/rpg-navigation/software/build/lib/python2.7/dist-packages:/home/marcelo/rpg-navigation/software/build/lib/python2.7/site-packages:${PYTHONPATH}
exec /usr/bin/python /home/marcelo/rpg-navigation/software/build/lib/python2.7/dist-packages/motion_estimate_scripts/spoof_driving_posture.py "$@"
